language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build vsphere-automation-appliance.gemspec
  - gem install ./vsphere-automation-appliance-0.4.3.gem
