language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build vsphere-automation-vapi.gemspec
  - gem install ./vsphere-automation-vapi-0.2.2.gem
